export default {
  lists: [],
  testLists: [],
  currentListId: null,
  currentListItems: [],
  currentListObj: null,
  currentListView: 'owner',
  edittingListObj: null,
  filteredList: [],
  currentSingleItem: null,
  edittingItemIndex: null,
  deletedLists: [],
  deletedItems: [],
  filters: {
    currentSearchValue: '',
    checkedTags: [],
    checkedCategories: [],
  },
  visualization: {
    sorting: 'dateCreated',
    mode: 'list',
    shuffleTrigger: false,
    listAlign: 'center',
    areItemDetailsShown: false,
    isItemsOrderReversed: false,
  },
  settings: {
    isItemFormInSidebar: false,
    isFocusOnList: false,
    isListUnderSidebar: true,
    isUsingHotkeys: true,
    theme: 'default',
  },
  sidebar: {
    isOpen: false,
    mode: 'lists',
  },
  notification: {
    time: null,
    text: '',
  },
  modalNameToShow: '',
  confirmationModalTitle: '',
  explicitRequestsNumber: 0,
};
