export default {
  lists: [],
  testLists: [],
  currentListId: null,
  currentListItems: [],
  currentSearchValue: '',
  edittingListObj: null,
  checkedTags: [],
  checkedCategories: [],
  edittingItemObj: null,
  deletedLists: [],
  deletedItems: [],
  visualization: {
    sorting: 'date created',
    mode: 'list',
    theme: 'default',
    shuffleTrigger: false,
    listAlign: 'center',
    areItemDetailsShown: false,
    isItemsOrderReversed: false,
  },
  settings: {
    isItemFormInSidebar: false,
    isFocusOnList: false,
    isListUnderSidebar: true,
    isUsingHotkeys: true,
  },
  sidebar: {
    isOpen: false,
    mode: 'lists',
  },
  notification: {
    time: null,
    text: '',
  },
  modalNameToShow: '',
  confirmationModalTitle: '',
  requestsNumber: 0,
};
