name: Dev deploy

on:
  push:
    branches: [ dev ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      env:
       NICKNAME: ${{ secrets.NICKNAME_GITHUB }}
       TOKEN: ${{ secrets.TOKEN_GITHUB }}
      with:
        host: ${{ secrets.HOST_SERVER }}
        username: ${{ secrets.NICKNAME_SERVER }}
        password: ${{ secrets.PASSWORD_SERVER }}
        port: ${{ secrets.PORT_SERVER }}
        envs: NICKNAME,TOKEN
        script_stop: true
        script: |
          source source /home/vyadl/nodevenv/dev.idli/14/bin/activate && cd /home/vyadl/dev.idli
