name: CI

on:
  push:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: server187.web-hosting.com
        username: vyadl
        password: persicumPatronum
        port: 21098
        script: |
          source /home/vyadl/nodevenv/idli/14/bin/activate && cd /home/vyadl/idli
          git pull "https://vyadl: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@github.com/vyadl/idli.git" master
          npm install
          npm run build
