name: CI

on:
  push:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_SERVER }}
        username: ${{ secrets.NICKNAME_SERVER }}
        password: ${{ secrets.PASSWORD_SERVER }}
        port: ${{ secrets.PORT_SERVER }}
        script: |
          source /home/vyadl/nodevenv/idli/14/bin/activate && cd /home/vyadl/idli
          run git pull "https://${{ secrets.NICKNAME_GITHUB }}:${{ secrets.TOKEN_GIHUB }}@github.com/vyadl/idli.git" master
          run npm install
          run npm run build
          
