name: CI

on:
  push:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      env:
       NICKNAME: ${{ secrets.NICKNAME_GITHUB }}
       TOKEN: ${{ secrets.TOKEN_GITHUB }}
      with:
        host: ${{ secrets.HOST_SERVER }}
        username: ${{ secrets.NICKNAME_SERVER }}
        password: ${{ secrets.PASSWORD_SERVER }}
        port: ${{ secrets.PORT_SERVER }}
        envs: NICKNAME,TOKEN
        script: |
          echo $NICKNAME
          echo $TOKEN
          source /home/vyadl/nodevenv/idli/14/bin/activate && cd /home/vyadl/idli
          git pull "https://$NICKNAME:$TOKEN@github.com/vyadl/idli.git" master
          npm install
          npm run build
          
